# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.21

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.21.3_1/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.21.3_1/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/vojtatom/Documents/metacity/src.nosync/Metacity

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/vojtatom/Documents/metacity/src.nosync/Metacity

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.21.3_1/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.21.3_1/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/vojtatom/Documents/metacity/src.nosync/Metacity/CMakeFiles /Users/vojtatom/Documents/metacity/src.nosync/Metacity//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/vojtatom/Documents/metacity/src.nosync/Metacity/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named primitive

# Build rule for target.
primitive: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 primitive
.PHONY : primitive

# fast build rule for target.
primitive/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/primitive.dir/build.make CMakeFiles/primitive.dir/build
.PHONY : primitive/fast

metacity/geometry/attributes.o: metacity/geometry/attributes.cpp.o
.PHONY : metacity/geometry/attributes.o

# target to build an object file
metacity/geometry/attributes.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/primitive.dir/build.make CMakeFiles/primitive.dir/metacity/geometry/attributes.cpp.o
.PHONY : metacity/geometry/attributes.cpp.o

metacity/geometry/attributes.i: metacity/geometry/attributes.cpp.i
.PHONY : metacity/geometry/attributes.i

# target to preprocess a source file
metacity/geometry/attributes.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/primitive.dir/build.make CMakeFiles/primitive.dir/metacity/geometry/attributes.cpp.i
.PHONY : metacity/geometry/attributes.cpp.i

metacity/geometry/attributes.s: metacity/geometry/attributes.cpp.s
.PHONY : metacity/geometry/attributes.s

# target to generate assembly for a file
metacity/geometry/attributes.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/primitive.dir/build.make CMakeFiles/primitive.dir/metacity/geometry/attributes.cpp.s
.PHONY : metacity/geometry/attributes.cpp.s

metacity/geometry/lines.o: metacity/geometry/lines.cpp.o
.PHONY : metacity/geometry/lines.o

# target to build an object file
metacity/geometry/lines.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/primitive.dir/build.make CMakeFiles/primitive.dir/metacity/geometry/lines.cpp.o
.PHONY : metacity/geometry/lines.cpp.o

metacity/geometry/lines.i: metacity/geometry/lines.cpp.i
.PHONY : metacity/geometry/lines.i

# target to preprocess a source file
metacity/geometry/lines.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/primitive.dir/build.make CMakeFiles/primitive.dir/metacity/geometry/lines.cpp.i
.PHONY : metacity/geometry/lines.cpp.i

metacity/geometry/lines.s: metacity/geometry/lines.cpp.s
.PHONY : metacity/geometry/lines.s

# target to generate assembly for a file
metacity/geometry/lines.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/primitive.dir/build.make CMakeFiles/primitive.dir/metacity/geometry/lines.cpp.s
.PHONY : metacity/geometry/lines.cpp.s

metacity/geometry/points.o: metacity/geometry/points.cpp.o
.PHONY : metacity/geometry/points.o

# target to build an object file
metacity/geometry/points.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/primitive.dir/build.make CMakeFiles/primitive.dir/metacity/geometry/points.cpp.o
.PHONY : metacity/geometry/points.cpp.o

metacity/geometry/points.i: metacity/geometry/points.cpp.i
.PHONY : metacity/geometry/points.i

# target to preprocess a source file
metacity/geometry/points.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/primitive.dir/build.make CMakeFiles/primitive.dir/metacity/geometry/points.cpp.i
.PHONY : metacity/geometry/points.cpp.i

metacity/geometry/points.s: metacity/geometry/points.cpp.s
.PHONY : metacity/geometry/points.s

# target to generate assembly for a file
metacity/geometry/points.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/primitive.dir/build.make CMakeFiles/primitive.dir/metacity/geometry/points.cpp.s
.PHONY : metacity/geometry/points.cpp.s

metacity/geometry/polygons.o: metacity/geometry/polygons.cpp.o
.PHONY : metacity/geometry/polygons.o

# target to build an object file
metacity/geometry/polygons.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/primitive.dir/build.make CMakeFiles/primitive.dir/metacity/geometry/polygons.cpp.o
.PHONY : metacity/geometry/polygons.cpp.o

metacity/geometry/polygons.i: metacity/geometry/polygons.cpp.i
.PHONY : metacity/geometry/polygons.i

# target to preprocess a source file
metacity/geometry/polygons.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/primitive.dir/build.make CMakeFiles/primitive.dir/metacity/geometry/polygons.cpp.i
.PHONY : metacity/geometry/polygons.cpp.i

metacity/geometry/polygons.s: metacity/geometry/polygons.cpp.s
.PHONY : metacity/geometry/polygons.s

# target to generate assembly for a file
metacity/geometry/polygons.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/primitive.dir/build.make CMakeFiles/primitive.dir/metacity/geometry/polygons.cpp.s
.PHONY : metacity/geometry/polygons.cpp.s

metacity/geometry/primitive.o: metacity/geometry/primitive.cpp.o
.PHONY : metacity/geometry/primitive.o

# target to build an object file
metacity/geometry/primitive.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/primitive.dir/build.make CMakeFiles/primitive.dir/metacity/geometry/primitive.cpp.o
.PHONY : metacity/geometry/primitive.cpp.o

metacity/geometry/primitive.i: metacity/geometry/primitive.cpp.i
.PHONY : metacity/geometry/primitive.i

# target to preprocess a source file
metacity/geometry/primitive.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/primitive.dir/build.make CMakeFiles/primitive.dir/metacity/geometry/primitive.cpp.i
.PHONY : metacity/geometry/primitive.cpp.i

metacity/geometry/primitive.s: metacity/geometry/primitive.cpp.s
.PHONY : metacity/geometry/primitive.s

# target to generate assembly for a file
metacity/geometry/primitive.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/primitive.dir/build.make CMakeFiles/primitive.dir/metacity/geometry/primitive.cpp.s
.PHONY : metacity/geometry/primitive.cpp.s

metacity/geometry/primitives.o: metacity/geometry/primitives.cpp.o
.PHONY : metacity/geometry/primitives.o

# target to build an object file
metacity/geometry/primitives.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/primitive.dir/build.make CMakeFiles/primitive.dir/metacity/geometry/primitives.cpp.o
.PHONY : metacity/geometry/primitives.cpp.o

metacity/geometry/primitives.i: metacity/geometry/primitives.cpp.i
.PHONY : metacity/geometry/primitives.i

# target to preprocess a source file
metacity/geometry/primitives.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/primitive.dir/build.make CMakeFiles/primitive.dir/metacity/geometry/primitives.cpp.i
.PHONY : metacity/geometry/primitives.cpp.i

metacity/geometry/primitives.s: metacity/geometry/primitives.cpp.s
.PHONY : metacity/geometry/primitives.s

# target to generate assembly for a file
metacity/geometry/primitives.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/primitive.dir/build.make CMakeFiles/primitive.dir/metacity/geometry/primitives.cpp.s
.PHONY : metacity/geometry/primitives.cpp.s

metacity/geometry/slicing.o: metacity/geometry/slicing.cpp.o
.PHONY : metacity/geometry/slicing.o

# target to build an object file
metacity/geometry/slicing.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/primitive.dir/build.make CMakeFiles/primitive.dir/metacity/geometry/slicing.cpp.o
.PHONY : metacity/geometry/slicing.cpp.o

metacity/geometry/slicing.i: metacity/geometry/slicing.cpp.i
.PHONY : metacity/geometry/slicing.i

# target to preprocess a source file
metacity/geometry/slicing.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/primitive.dir/build.make CMakeFiles/primitive.dir/metacity/geometry/slicing.cpp.i
.PHONY : metacity/geometry/slicing.cpp.i

metacity/geometry/slicing.s: metacity/geometry/slicing.cpp.s
.PHONY : metacity/geometry/slicing.s

# target to generate assembly for a file
metacity/geometry/slicing.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/primitive.dir/build.make CMakeFiles/primitive.dir/metacity/geometry/slicing.cpp.s
.PHONY : metacity/geometry/slicing.cpp.s

metacity/geometry/triangulation.o: metacity/geometry/triangulation.cpp.o
.PHONY : metacity/geometry/triangulation.o

# target to build an object file
metacity/geometry/triangulation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/primitive.dir/build.make CMakeFiles/primitive.dir/metacity/geometry/triangulation.cpp.o
.PHONY : metacity/geometry/triangulation.cpp.o

metacity/geometry/triangulation.i: metacity/geometry/triangulation.cpp.i
.PHONY : metacity/geometry/triangulation.i

# target to preprocess a source file
metacity/geometry/triangulation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/primitive.dir/build.make CMakeFiles/primitive.dir/metacity/geometry/triangulation.cpp.i
.PHONY : metacity/geometry/triangulation.cpp.i

metacity/geometry/triangulation.s: metacity/geometry/triangulation.cpp.s
.PHONY : metacity/geometry/triangulation.s

# target to generate assembly for a file
metacity/geometry/triangulation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/primitive.dir/build.make CMakeFiles/primitive.dir/metacity/geometry/triangulation.cpp.s
.PHONY : metacity/geometry/triangulation.cpp.s

metacity/geometry/types.o: metacity/geometry/types.cpp.o
.PHONY : metacity/geometry/types.o

# target to build an object file
metacity/geometry/types.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/primitive.dir/build.make CMakeFiles/primitive.dir/metacity/geometry/types.cpp.o
.PHONY : metacity/geometry/types.cpp.o

metacity/geometry/types.i: metacity/geometry/types.cpp.i
.PHONY : metacity/geometry/types.i

# target to preprocess a source file
metacity/geometry/types.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/primitive.dir/build.make CMakeFiles/primitive.dir/metacity/geometry/types.cpp.i
.PHONY : metacity/geometry/types.cpp.i

metacity/geometry/types.s: metacity/geometry/types.cpp.s
.PHONY : metacity/geometry/types.s

# target to generate assembly for a file
metacity/geometry/types.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/primitive.dir/build.make CMakeFiles/primitive.dir/metacity/geometry/types.cpp.s
.PHONY : metacity/geometry/types.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... primitive"
	@echo "... metacity/geometry/attributes.o"
	@echo "... metacity/geometry/attributes.i"
	@echo "... metacity/geometry/attributes.s"
	@echo "... metacity/geometry/lines.o"
	@echo "... metacity/geometry/lines.i"
	@echo "... metacity/geometry/lines.s"
	@echo "... metacity/geometry/points.o"
	@echo "... metacity/geometry/points.i"
	@echo "... metacity/geometry/points.s"
	@echo "... metacity/geometry/polygons.o"
	@echo "... metacity/geometry/polygons.i"
	@echo "... metacity/geometry/polygons.s"
	@echo "... metacity/geometry/primitive.o"
	@echo "... metacity/geometry/primitive.i"
	@echo "... metacity/geometry/primitive.s"
	@echo "... metacity/geometry/primitives.o"
	@echo "... metacity/geometry/primitives.i"
	@echo "... metacity/geometry/primitives.s"
	@echo "... metacity/geometry/slicing.o"
	@echo "... metacity/geometry/slicing.i"
	@echo "... metacity/geometry/slicing.s"
	@echo "... metacity/geometry/triangulation.o"
	@echo "... metacity/geometry/triangulation.i"
	@echo "... metacity/geometry/triangulation.s"
	@echo "... metacity/geometry/types.o"
	@echo "... metacity/geometry/types.i"
	@echo "... metacity/geometry/types.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

