from typing import List, Tuple

class LegoBuilder:
    def __init__(self) -> None: ...
    def build_heightmap(self, arg0: float, arg1: float, arg2: float, arg3: float, arg4: int) -> None: ...
    def insert_model(self, arg0: SimpleMultiPolygon) -> None: ...
    def lego_to_png(self, arg0: str) -> None: ...
    def legofy(self, arg0: int) -> json: ...

class MultiLine(Primitive):
    def __init__(self) -> None: ...
    def deserialize(self, arg0: json) -> None: ...
    def push_l2(self, arg0: List[float]) -> None: ...
    def push_l3(self, arg0: List[float]) -> None: ...
    def serialize(self) -> json: ...
    def transform(self) -> SimplePrimitive: ...
    @property
    def type(self) -> str: ...

class MultiPoint(Primitive):
    def __init__(self) -> None: ...
    def deserialize(self, arg0: json) -> None: ...
    def push_p2(self, arg0: List[float]) -> None: ...
    def push_p3(self, arg0: List[float]) -> None: ...
    def serialize(self) -> json: ...
    def transform(self) -> SimplePrimitive: ...
    @property
    def type(self) -> str: ...

class MultiPolygon(Primitive):
    def __init__(self) -> None: ...
    def deserialize(self, arg0: json) -> None: ...
    def push_p2(self, arg0: List[List[float]]) -> None: ...
    def push_p3(self, arg0: List[List[float]]) -> None: ...
    def serialize(self) -> json: ...
    def transform(self) -> SimplePrimitive: ...
    @property
    def type(self) -> str: ...

class MultiTimePoint(Primitive):
    def __init__(self) -> None: ...
    def deserialize(self, arg0: json) -> None: ...
    def serialize(self) -> json: ...
    def set_points_from_b64(self, arg0: str) -> None: ...
    def set_start_time(self, arg0: int) -> None: ...
    def transform(self) -> SimplePrimitive: ...
    @property
    def type(self) -> str: ...

class Primitive:
    def __init__(self) -> None: ...
    def deserialize(self, arg0: json) -> None: ...
    def serialize(self) -> json: ...
    def transform(self) -> SimplePrimitive: ...
    @property
    def type(self) -> str: ...

class SimpleMultiLine(SimplePrimitive):
    def __init__(self) -> None: ...
    def add_attribute(self, arg0: str, arg1: int) -> None: ...
    def copy(self) -> SimplePrimitive: ...
    def map(self, arg0: SimpleMultiPolygon) -> None: ...
    def slice_to_grid(self, arg0: float) -> List[SimplePrimitive]: ...
    def to_obj(self, arg0: str, arg1: int) -> int: ...
    @property
    def type(self) -> str: ...

class SimpleMultiPoint(SimplePrimitive):
    def __init__(self) -> None: ...
    def copy(self) -> SimplePrimitive: ...
    def map(self, arg0: SimpleMultiPolygon) -> None: ...
    def slice_to_grid(self, arg0: float) -> List[SimplePrimitive]: ...
    def to_obj(self, arg0: str, arg1: int) -> int: ...
    @property
    def type(self) -> str: ...

class SimpleMultiPolygon(SimplePrimitive):
    def __init__(self) -> None: ...
    def copy(self) -> SimplePrimitive: ...
    def map(self, arg0: SimpleMultiPolygon) -> None: ...
    def slice_to_grid(self, arg0: float) -> List[SimplePrimitive]: ...
    def to_obj(self, arg0: str, arg1: int) -> int: ...
    @property
    def type(self) -> str: ...

class SimplePrimitive(Primitive):
    def __init__(self) -> None: ...
    def add_attribute(self, arg0: str, arg1: int) -> None: ...
    def copy(self) -> SimplePrimitive: ...
    def deserialize(self, arg0: json) -> None: ...
    def join(self, arg0: SimplePrimitive) -> None: ...
    def map(self, arg0: SimpleMultiPolygon) -> None: ...
    def serialize(self) -> json: ...
    def serialize_stream(self) -> json: ...
    def shift(self, arg0: float, arg1: float, arg2: float) -> None: ...
    def slice_to_grid(self, arg0: float) -> List[SimplePrimitive]: ...
    def to_obj(self, arg0: str, arg1: int) -> int: ...
    def transform(self) -> SimplePrimitive: ...
    @property
    def bounding_box(self) -> Tuple[Tuple[float,float,float],Tuple[float,float,float]]: ...
    @property
    def centroid(self) -> Tuple[float,float,float]: ...
    @property
    def type(self) -> str: ...
