name: Metacity CI

on:
  push:
    branches: [ release, dev ]
  pull_request:
    branches: [ dev ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install system requirements
      run: |
        sudo add-apt-repository ppa:ubuntugis/ppa
        sudo apt-get update
        sudo apt-get install gdal-bin
        sudo apt-get install libgdal-dev
        export CPLUS_INCLUDE_PATH=/usr/include/gdal
        export C_INCLUDE_PATH=/usr/include/gdal
        sudo apt-get install cmake
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Build Geometry package
      run: |
        python setup.py build_ext --inplace
    - name: Test with pytest
      run: |
        pytest tests/* --cov=metacity
    - name: Upload to Coveralls
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
      run: |
        pip install coveralls
        coveralls

  tag:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && contains(github.ref, 'release')
    needs: test
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: "Get release version"
      run: |
        CURRENT_VERSION=$(python3 setup.py --version) 
        echo "Current version: $CURRENT_VERSION"
        echo "::set-env name=CURRENT_VERSION::v$CURRENT_VERSION"
    - uses: rickstaa/action-create-tag@v1
      with:
        tag: ${{ env.CURRENT_VERSION }}

