name: Metacity CI

on:
  push:
    branches: [ release, dev ]
  pull_request:
    branches: [ dev ]


env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov

    - name: Build Geometry package
      run: |
        pip install .

    - name: Test with pytest
      run: |
        pytest ./tests/* --cov=metacity

    - name: Upload to Coveralls
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
      run: |
        pip install coveralls
        coveralls

  build-image:
    name: Build Docker Image test
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}


  make-wheels:
    name: Make ${{ matrix.os }} wheels
    if: github.event_name == 'push' && contains(github.ref, 'release')
    needs: build-image
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["macos-latest", "ubuntu-latest", "windows-latest"]
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: "Build wheels"
        uses: pypa/cibuildwheel@v2.9.0

      - name: Verify clean directory
        run: git diff --exit-code
        shell: bash

      - name: "Upload wheel as artifact"
        uses: actions/upload-artifact@v3
        with:
          name: artifact-${{ matrix.os }}-wheel
          path: ./wheelhouse/*.whl


  make-sdist:
    name: Make source distribution
    if: github.event_name == 'push' && contains(github.ref, 'release')
    needs: build-image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Build SDist
      run: pipx run build --sdist

    - name: Check metadata
      run: pipx run twine check dist/*

    - uses: actions/upload-artifact@v3
      with:
        name: artifact-source-dist
        path: dist/*.tar.gz


  tag-and-release:
    name: Tag commit and create a release
    needs: [make-wheels, make-sdist]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install scikit-build

    - name: "Get release version"
      run: |
        CURRENT_VERSION=$(python3 setup.py --version | tail -1) 
        echo "Current version: $CURRENT_VERSION"
        echo "CURRENT_VERSION=v$CURRENT_VERSION" >> $GITHUB_ENV

    - uses: rickstaa/action-create-tag@v1
      with:
        tag: ${{ env.CURRENT_VERSION }}

    - uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        generateReleaseNotes: true
        tag: ${{ env.CURRENT_VERSION }}


  upload:
    name: Upload to PyPI
    needs: tag-and-release
    runs-on: ubuntu-latest
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v3
      with:
        path: dist

    - name: Copy artifacts to dist/ folder
      run: |
        echo "* Downloaded artifacts:"
        ls dist/
        cd dist/
        echo "* Copying artifacts to dist/ folder:"
        find . -mindepth 2 -maxdepth 2 -type f -print -exec mv {} . \;
        echo "* Deleting empty directories:"
        find . -maxdepth 1 -type d -empty -print -exec rmdir {} +
        cd ..
        echo "* Prepared artifacts:"
        ls dist/

    - name: Publish package
      uses: pypa/gh-action-pypi-publish@v1.5.0
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}


  build-and-push-image:
    name: Upload to Container Registry
    runs-on: ubuntu-latest
    needs: tag-and-release
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  