name: Metacity Release CI

on:  
  push:
    tags: 
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: 'see ref'
      run: |
        echo "ref: {{ github.ref }}"
    - uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        generateReleaseNotes: true
