name: Metacity Release CI

on:  
  push:
    tags: 
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    if: contains(github.ref, 'main')
    steps:
    - uses: actions/checkout@v2
    - uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        generateReleaseNotes: true
