name: Metacity Deploy CI

on:  
  push:
    tags: 
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && contains(github.ref, 'main')
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        generateReleaseNotes: true
