name: "Publish to Container Registry"

on:
  workflow_dispatch: {}

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  version:
    name: Get version to ENV
    needs: [make-wheels, make-sdist]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install scikit-build

    - name: "Get release version"
      run: |
        CURRENT_VERSION=$(python3 setup.py --version) 
        echo "Current version: $CURRENT_VERSION"
        echo "CURRENT_VERSION=v$CURRENT_VERSION" >> $GITHUB_ENV

  